### ISSUE TITLE
Special chars converted to ?

### ISSUE THREAD

**Issue by 0xC4N1** [Knils/atom-tabletopsimulator-lua#9]
When I paste a ☑ in-game or in Notepad++ and apply the script to the game, it will be displayed correctly. However when I do the same with the Atom editor and the TTS plugin, the ☑ converts to question marks.

**Comment by tjakubo2** [comment]
Use 
`\u{XXXX}`
where XXXX is hex code for the special char.

Looks like yours is
`\u{2611}`
